### ISSUE TITLE
Selecting a maintainer for ansible-playbook-sensu and friends

### ISSUE THREAD

**Issue by nhooey** [Mayeu/mxl#1]
Hey Matthieu,

I sent you an email, but I haven't heard back.

There are a lot of pull requests for the following repositories:
- ansible-playbook-sensu
- ansible-playbook-rabbitmq

But we haven't heard from you or seen any merged in a while.

Would you be open to having someone else maintain those repositories for you?

Thanks,
- Neil

**Comment by Mayeu** [comment]
Hello,

I have a plan of upgrading and reorganizing/refactoring those projects (planning a V2 for both of those since they are related anyway).

My current "timeline" for upgrade (can't promise anything here, after all "_THIS SOFTWARE IS PROVIDED 'AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES_" ;) ), will be to upgrade those around May. Since I'll be finally upgrading some of my Ubuntu server to the last version, I'll have to work on both of those anyway :)

Closing this, since it's not related to mxl.
